### ISSUE TITLE
Data Builder it's preventing record creation in some Custom Table

### ISSUE THREAD

**Issue by alacret** [8base/issues#10]
**Describe the bug**
I created a new Table call UserInformation (description in the screenshot), the table does not have any records. The UI does not show me any error.

**To Reproduce**
Steps to reproduce the behavior: (In my workspace)
1. Go to Data Builder, my UserInformation Table
2. Click on Add Row
3. Fill mandatory Fields
4. Click Add
5. See error

**Screenshots**
![screen shot 2018-12-09 at 12 46 41 pm](https://user-images.githubusercontent.com/918895/49700720-8b9df180-fbb0-11e8-8977-5a0e1e549494.png)
![screen shot 2018-12-09 at 12 46 54 pm](https://user-images.githubusercontent.com/918895/49700722-8e004b80-fbb0-11e8-9ad6-130b51868d92.png)

![screen shot 2018-12-09 at 12 42 59 pm](https://user-images.githubusercontent.com/918895/49700707-67daab80-fbb0-11e8-97df-1d12c0d79afc.png)

**Comment by andr11111** [comment]
This is fixed. We added a UI message asking to confirm deletion of records.
