### ISSUE TITLE
API "Files" Documentation Missing

### ISSUE THREAD

**Issue by AlanThinks** [8base/issues#13]
**Describe the bug**
What is the best way to upload files to 8base?

**To Reproduce**
https://docs.8base.com/docs/schema-management

**Screenshots**
<img width="537" alt="image" src="https://user-images.githubusercontent.com/28021164/49704557-6629db80-fbe2-11e8-8acb-c8bca4750a25.png">

**Comment by andr11111** [comment]
Fixed https://docs.8base.com/docs/files-api
