### ISSUE TITLE
Invitations Screen Date Bug

### ISSUE THREAD

**Issue by AlanThinks** [8base/issues#19]
**Describe the bug**
Wrong date being displayed in Invitation Screen (9/01/2019), Also - most of these invitations have already been accepted, should they still display here? or would it be good if it said "accepted" or "no response" for example?

**Screenshots**
![shot](https://user-images.githubusercontent.com/28021164/50911620-3d258200-13fe-11e9-9508-af21a9d85ed2.jpg)

**Comment by zouxuoz** [comment]
Fixed
