### ISSUE TITLE
Delete error does not explain situation

### ISSUE THREAD

**Issue by alacret** [8base/issues#2]
**Describe the bug**
I created a UserInformation table, with a relationship with the User Table. This relationship is desired to be a One to One relationship, meaning it doesn't allow multiple UserInformation per User, and this is how is setup currently.

When I try to delete a UserInformation row, the UI doesn't do anything, and in the console appears this:

![screen shot 2018-12-05 at 11 18 58 pm](https://user-images.githubusercontent.com/918895/49561293-83119680-f8e4-11e8-843b-304b50a4de8c.png)

**To Reproduce**
1. Create a Table, with a `user` field related to the system table User. Do not allow multiple values
2. Create a row in the table
3. Try to delete the Row

**Expected behavior**
If there is a consistency error it should be shown. But I think that in this case there isn't

**Comment by andr11111** [comment]
We changed the error message text to be more clear.
