### ISSUE TITLE
Side effects on Mandatory and default value constraints

### ISSUE THREAD

**Issue by alacret** [8base/issues#24]
**Describe the bug**
When a field that already exists is set `MANDATORY` with a Default Value, it overrides all the values on that column.

**To Reproduce**
1. Create A table
2. Create a non-mandatory non-default value Field
3. Create some Rows with and without value on the Field
4. Edit Field: set Mandatory with a Default Value

**Expected behavior**
The system should set Default Value only in Null values of the Column

**Comment by esemushin** [comment]
fixed
