### ISSUE TITLE
npm install of demo app fails

### ISSUE THREAD

**Issue by mindgutter** [8base/issues#25]
When trying to install sample app i ran into trouble. Logs attached. 
[2019-01-26T23_02_08_350Z-debug.log](https://github.com/8base/issues/files/2799625/2019-01-26T23_02_08_350Z-debug.log)
[2019-01-26T23_07_24_248Z-debug.log](https://github.com/8base/issues/files/2799626/2019-01-26T23_07_24_248Z-debug.log)

**Comment by andr11111** [comment]
@mindgutter thanks for letting us know. We will investigate and let you how to resolve.

**Comment by andr11111** [comment]
@mindgutter we tried on multiple machines (including with OS matching yours) and were not able to reproduce the issue. I updated the dependencies to latest versions. I suggest that you try deleting `node_modules` and pulling the repo. Or just pull it into a new folder from scratch and then run `npm install` again. Please let me know if the issue persists and we'll dig deeper.
