### ISSUE TITLE
File-Input does not work properly with maxFiles greater then 1

### ISSUE THREAD

**Issue by alacret** [8base/issues#26]
**Describe the bug**
When MaxFiles prop is more than 1, it does not return the `values` parameter in the children function

It presents also this warning:
store.js:238 Upload in background can be enabled only when transformations are disabled

**Comment by zouxuoz** [comment]
@alacret can't reproduce - https://www.screencast.com/t/GLkP39SsOn3W

P.S You should use `value`, not `values` parameter.
