### ISSUE TITLE
UI Multi select Problem

### ISSUE THREAD

**Issue by alacret** [8base/issues#29]
![screen shot 2019-02-22 at 1 56 12 pm](https://user-images.githubusercontent.com/918895/53264495-ba087480-36a9-11e9-8055-3b5b06240e74.png)

**Comment by alacret** [comment]
![screen shot 2019-02-22 at 1 58 39 pm](https://user-images.githubusercontent.com/918895/53264593-fcca4c80-36a9-11e9-95a9-065599007671.png)

**Comment by zouxuoz** [comment]
@alacret already fixed in the 8base/boost, in our app will be fixed in closest release
