### ISSUE TITLE
Self-signup request

### ISSUE THREAD

**Issue by abranhe** [8base/issues#31]
I would be great to have the possibility to signup, I am from Mangohacks and our team requested support for that but you guys told us that the feature will be released soon. 

<img width="862" alt="Screen Shot 2019-03-28 at 8 57 48 AM" src="https://user-images.githubusercontent.com/21347264/55159715-168f0180-5138-11e9-9d11-7e60eb9cb6ab.png">

**Comment by andr11111** [comment]
Yes, this feature is in the final stages and should be released in the next couple of weeks.
