### ISSUE TITLE
User List overflow in 8base app

### ISSUE THREAD

**Issue by alacret** [8base/issues#32]
![Screen Shot 2019-03-28 at 2 35 04 PM](https://user-images.githubusercontent.com/918895/55183692-c9765400-5166-11e9-8173-a62c12b214da.png)

**Comment by alacret** [comment]
![Screen Shot 2019-03-28 at 2 37 00 PM](https://user-images.githubusercontent.com/918895/55183794-fc204c80-5166-11e9-9389-c02511a8ea72.png)

**Comment by zouxuoz** [comment]
Fixed
