### ISSUE TITLE
Error updating a required Field

### ISSUE THREAD

**Issue by alacret** [8base/issues#36]
When I try to update a required field it throws this error:

![Screen Shot 2019-04-09 at 11 13 46 AM](https://user-images.githubusercontent.com/918895/55812242-a0d05180-5ab8-11e9-9872-bb234a143190.png)

The workaround is to remove Mandatory constraint

**Comment by andr11111** [comment]
@alacret what would be the expected behavior here? I assume this is because `currency.alliance` is a required relationship. Do you need the currency record to be automatically deleted in this case?

**Comment by alacret** [comment]
If I understand correctly the platform is doing a disconnect and connect. That’s why the error raises. 

However when I’m interacting with the API a connect operation allows me to replace the relationship without raising any error. 

I would spect that the mandatory constraint don’t allow me to leave the field blank or null but that would allow me to update the value as well

**Comment by andr11111** [comment]
Makes, sense, I understand the problem. Thanks for reporting!
