### ISSUE TITLE
File URL on File Input

### ISSUE THREAD

**Issue by alacret** [8base/issues#37]
**Is your feature request related to a problem? Please describe.**
When a file is uploaded, it would be a good idea to have the URL of the File that was uploaded. For preview purposes mainly

**Describe the solution you'd like**
None

**Describe alternatives you've considered**
https://developer.mozilla.org/en-US/docs/Web/API/FileReader/readAsDataURL#JavaScript

**Additional context**
![Screen Shot 2019-04-14 at 11 14 47 PM](https://user-images.githubusercontent.com/918895/56105614-1ef28500-5f0b-11e9-893e-c07e43d7c536.png)

**Comment by vorobeez** [comment]
@alacret You can use [createObjectURL](https://developer.mozilla.org/en-US/docs/Web/API/URL/createObjectURL) function to generate a url from a file.

**Comment by alacret** [comment]
@vorobeez we already solved like this:

```
render() {
...
    if (pictureUrl) pictureUrlToShow = pictureUrl;
    else if (avatar) pictureUrlToShow = avatar.downloadUrl;
...
return (
...
          <FileInput
            onChange={(picture, file, ...rest) => {
              const reader = new FileReader();
              reader.addEventListener(
                'load',
                () => {
                  onChange('pictureUrl', reader.result);
                },
                false,
              );
              reader.readAsDataURL(file);
              onChange('avatar', picture);
            }}
            value={'input.value'}
            maxFiles={1}>
            {({ pick, originalFile, ...rest }) => {
              return (
                <Column stretch justifyContent="center" alignItems="center">
                  <ImgUpload onClick={pick} url={pictureUrlToShow} />
                </Column>
              );
            }}
          </FileInput>
...
);
```
