### ISSUE TITLE
CreateMany Type incomplete after update

### ISSUE THREAD

**Issue by alacret** [8base/issues#38]
**Describe the bug**
The *createMany mutation lacks the fields of the *create Type:

![Screen Shot 2019-04-17 at 12 17 07 AM](https://user-images.githubusercontent.com/918895/56260742-6103fe00-60a6-11e9-9de7-b9348b8914ed.png)

![Screen Shot 2019-04-17 at 12 16 51 AM](https://user-images.githubusercontent.com/918895/56260731-58132c80-60a6-11e9-8f9a-abe5db1f6099.png)

**Comment by zouxuoz** [comment]
@alacret  `createMany` mutations don't support relation fields, but we plan to do it.
