### ISSUE TITLE
Data Builder & Functions  <Buttons> Don't Work

### ISSUE THREAD

**Issue by AlanThinks** [8base/issues#4]
**Describe the bug**
I've tested in Chrome and Safari, in the main page of the platform - The buttons DATA BUILDER and FUNCTIONS don't work, so I have to go to the side navigation.

**Screenshots**
![image](https://user-images.githubusercontent.com/28021164/49690056-b593dd00-faf8-11e8-8275-06565f2c66ca.png)

**Desktop (please complete the following information):**
 - OS: MACOS 10.14.1
 - Browse: Chrome & Safari

**Comment by zouxuoz** [comment]
@AlanThinks thx for the catch, fixed
