### ISSUE TITLE
Unable To delete User from Workspace

### ISSUE THREAD

**Issue by alacret** [8base/issues#40]
<img width="1680" alt="Screen Shot 2019-05-19 at 12 59 21 PM" src="https://user-images.githubusercontent.com/918895/57985439-0c053000-7a36-11e9-8b9a-192e6e12a4d3.png">
<img width="1680" alt="Screen Shot 2019-05-19 at 12 59 28 PM" src="https://user-images.githubusercontent.com/918895/57985440-0e678a00-7a36-11e9-88cc-7e2b38f11444.png">
<img width="1680" alt="Screen Shot 2019-05-19 at 12 59 45 PM" src="https://user-images.githubusercontent.com/918895/57985441-10c9e400-7a36-11e9-9761-4ce42839f705.png">

**Comment by zouxuoz** [comment]
Fixed

**Comment by zouxuoz** [comment]
Fixed
