### ISSUE TITLE
Unable to import a csv of Users from another Database

### ISSUE THREAD

**Issue by Bia3** [8base/issues#42]
**Describe the bug**
When importing a CSV file to the Users database the is8base field is required but not defined by UserCreateManyInput

**To Reproduce**
Import a CSV to the Users database

**Expected behavior**
To have the ability to import CSV to the Users database

**Screenshots**
![Screenshot1](https://user-images.githubusercontent.com/8649724/60754158-4ef57580-9f9a-11e9-8c41-2d9c41d645c5.png)
![Screenshot2](https://user-images.githubusercontent.com/8649724/60754159-50bf3900-9f9a-11e9-87b4-2e5133641b46.png)

**Desktop (please complete the following information):**
 - OS: Linux pop-os 5.0.0-15-generi
 - Browser: Firefox
 - Version: 67.0.4

**Comment by zouxuoz** [comment]
@Bia3 Thank you for your report. We will fix that in the nearest future.

**Comment by zouxuoz** [comment]
@Bia3 Fixed
