### ISSUE TITLE
npm vs. yarn

### ISSUE THREAD

**Issue by heymartinadams** [8base/issues#44]
**Is your feature request related to a problem? Please describe.**
Minor feature: during deploy, we get the following message: `File package-lock.json is missing. Consider adding it to enable fast deploy.`

**Describe the solution you'd like**
Many developers use `yarn` instead of `npm`, and yarn creates `yarn.lock` instead of `package-lock.json`.

This is so trivial, perhaps I shouldn’t even have mentioned it. Just for your consideration.

**Comment by zouxuoz** [comment]
@heymartinadams Thank you for the report. We don't have a task for yarn support for fast deploy in our roadmap now, but we will investigate the the complexity of this task nearest future.

**Comment by eugeneantonevich** [comment]
@heymartinadams We have researched implementation of this feature and decided to release it on the next week

**Comment by heymartinadams** [comment]
Thanks, @eugeneantonevich ✨

ps: what’s your policy on closing issues — should I be closing issues I’ve opened once addressed or resolved, or will you be doing this?

**Comment by eugeneantonevich** [comment]
@heymartinadams We will close issues by ourself, thank you.
