### ISSUE TITLE
System Table Users: Cannot Update User

### ISSUE THREAD

**Issue by AlanThinks** [8base/issues#5]
**Describe the bug**
Cannot Update information in System Table *Users*

**To Reproduce**
1. Go to Data Builder
2. Go to System Tables > Users
3. Edit an existing user and change any information
4. Click *Submit Changes*
5. It does nothing 👈

**Screenshots**
![image](https://user-images.githubusercontent.com/28021164/49690013-f2130900-faf7-11e8-84f2-64aa959c397d.png)

**Desktop (please complete the following information):**
 - OS:MacOS 10.14.1
 - Browser: Chrome and Safari

**Comment by zouxuoz** [comment]
Fixed
