### ISSUE TITLE
Unable to add fields to Users table in dashboard

### ISSUE THREAD

**Issue by heymartinadams** [8base/issues#50]
**Describe the bug**
Dashboard prevents the addition of custom fields in `Users` system table

**To Reproduce**
1. Go to `Users` system table.
2. Try to add a new custom field.

**Expected behavior**
Should be able to add custom fields.

**Screenshots**
![image](https://user-images.githubusercontent.com/11673745/61490114-0ad27f80-a961-11e9-9c46-7135e36fc1de.png)

**Desktop (please complete the following information):**
 - macOS
 - Chrome 75

**Comment by zouxuoz** [comment]
@heymartinadams Thank you for the report. Fixed.
