### ISSUE TITLE
Unable to make field mandatory

### ISSUE THREAD

**Issue by heymartinadams** [8base/issues#51]
**Describe the bug**
Unable to make field in table with existing data mandatory. Receive the following error:
```json
"Variable "$data" got invalid value
{
  id: "5d3112e008693186ea07bb68",
  name: "email",
  displayName: "email",
  description: null,
  fieldType: "TEXT",
  fieldTypeAttributes: {
    format: "UNFORMATTED",
    fieldSize: 100,
    __typename: "TextFieldTypeAttributes"
  },
  isList: false,
  isRequired: true,
  isUnique: true,
  defaultValue: null,
  __typename: "TableField",
  initialValue: "test@test.com"
};
Field "__typename" is not defined by type TableFieldUpdateInput."
```

**To Reproduce**
1. Populate table with data.
2. Create optional `Text` field in table.
3. Click *Save*
4. Check *Mandatory* on same field, and click *Save*. Do _not_ fill in `Default Value` for now.
5. Popup appears:
![image](https://user-images.githubusercontent.com/11673745/61501627-e6889a00-a984-11e9-8ec0-b21ce36b704a.png)
6. Enter initial value and click *Update Field*.

**Expected behavior**
Table is supposed to allow field to be made mandatory and add initial value to records.

**Screenshots**

**Desktop (please complete the following information):**
 - macOS Chrome 75

**Comment by zouxuoz** [comment]
@heymartinadams Thank you for the report. Fixed.
