### ISSUE TITLE
Typo on new Docs

### ISSUE THREAD

**Issue by alacret** [8base/issues#58]
<img width="1680" alt="Screen Shot 2019-08-09 at 10 16 56 AM" src="https://user-images.githubusercontent.com/918895/62785892-866eaa80-ba8f-11e9-9171-6179a71c7590.png">

**Comment by heymartinadams** [comment]
Looks like this issue can be closed. 👍  https://github.com/8base/Documentation/commit/8d21e4172c16c2ebff4efd1b0521a29decfbc500#diff-b4f3573b2f24d5af026c33acf52ff716
