### ISSUE TITLE
“No Duplicate Values” option doesn’t work

### ISSUE THREAD

**Issue by heymartinadams** [8base/issues#59]
**Describe the bug**
A field for a table with existing data and unique values for that particular field cannot be set to *No Duplicate Values*. It returns an error.

**To Reproduce**
In this [workspace ID](https://app.8base.com/cjy0lrbqt000201mgd3zw8f8k)...
1. Go to `Venue` table.
2. Click on `venueId` field.
3. Attempt to set `No Duplicate Values`
4. See error.

**Expected behavior**
Expect to be able to make `No Duplicate Values` as `true`.

**Screenshots**
<img width="840" alt="Screen Shot 2019-09-07 at 11 56 59 AM" src="https://user-images.githubusercontent.com/11673745/64479110-212dd800-d167-11e9-992b-58b69c0920ce.png">
<img width="968" alt="Screen Shot 2019-09-07 at 11 56 41 AM" src="https://user-images.githubusercontent.com/11673745/64479118-29861300-d167-11e9-9dd9-1e6b5e7f2e37.png">
<img width="538" alt="Screen Shot 2019-09-07 at 11 56 47 AM" src="https://user-images.githubusercontent.com/11673745/64479107-170bd980-d167-11e9-9111-6bd5ef0fb122.png">

**Desktop (please complete the following information):**
 - macOS, Chrome 74

**Comment by heymartinadams** [comment]
My guess is that this issue and #45 have the same cause: in both cases, previously deleted data is maintained in 8base, but merely invisible to us, the client. Thus, if we try to update a field by making it mandatory or unique, for example, we are prevented from doing so because data we might have previously entered (and then deleted), but now invisible to us, is counted towards the mandatory/unique assessment.

If this is indeed how 8base handles data management, this is also problematic for *privacy* reasons. For example, GDPR requires us to be able to fully delete our customers’ data upon their request; thus, 8base needs to fully delete any data we delete, and not just make it invisible to us.

**Comment by sebscholl** [comment]
Hey @heymartinadams - this is a great insight that I'm going to look into with the team. Thank you for bringing it up! I'll check back in as soon as I have answers.

**Comment by heymartinadams** [comment]
Thanks, @sebscholl. Another thing that’s somewhat confusing is that the 8base interface uses our field labels, but for the actual querying, uses system field labels.

For example, as a convention, we capitalize our `relation` fields: the `Event` table has an `EventLodgings` field that connects to the `EventLodging` table in a one-to-many relation. However, when using the GraphQL query in the front-end app, we need to query the `eventLodgings` field.

**Comment by sebscholl** [comment]
Hey @heymartinadams yeah we are just trying to make it as universal as possible. Has it been an inconvenience/problem, or more of a "I'd prefer if...".

FYI, started a thread in the community on deletes!

https://community.8base.com/t/feature-idea-for-hard-delete-vs-soft-delete/83

**Comment by heymartinadams** [comment]
Great, thanks, @sebscholl. Will discuss in forum.

There’s no workaround for this bug (as I cannot view or access soft-deleted data — and thus cannot hard-delete data to prevent non-unique values), so will leave issue active for the moment.
