### ISSUE TITLE
Allow filter on update operations

### ISSUE THREAD

**Issue by alacret** [8base/issues#7]
**Is your feature request related to a problem? Please describe.**
Currently, I'm unable to update a set of objects unless I provide the ID of the object. 

**Describe the solution you'd like**
Allow the field ID of the <>UpdateInput to be optional, and add a filter to the mutations to conditionally update objects

**Describe alternatives you've considered**
First Filter with a query and then do a for each on every result

**Comment by andr11111** [comment]
This one is covered in https://github.com/8base/issues/issues/6 . Closing.
