### ISSUE TITLE
In Roles/Permissions Settings Buttons Don't Work

### ISSUE THREAD

**Issue by AlanThinks** [8base/issues#8]
**Describe the bug**
Cannot switch between the buttons `DATA, APPS, USERS`

**To Reproduce**
1. Settings
2. Roles
3. Click Role title to go into it's permissions settings
4. Buttons at the top don't work.

**Screenshots**
![image](https://user-images.githubusercontent.com/28021164/49698847-95672b00-fb97-11e8-9a4d-e38427256dc8.png)

**Browser**
Chrome/MacOS

**Comment by zouxuoz** [comment]
@AlanThinks thx for the catch, fixed
