### ISSUE TITLE
API won't allow any creation (*CreateInput)

### ISSUE THREAD

**Issue by alacret** [8base/issues#9]
**Describe the bug**
The API Does not let us do any create operations, even of I'm the owner of the workspace

**To Reproduce**
1. Go to API EXPLORER
2. Create a mutation of the type *CreatInput, example: orderCreate: OrderCreateInput
3. See "Don't have permissions error"

**Expected behavior**
The system should allow creating records from the API

**Screenshots**
![screen shot 2018-12-09 at 12 30 21 pm 1](https://user-images.githubusercontent.com/918895/49700652-9c019c80-fbaf-11e8-9a33-0057dc23183a.png)

![screen shot 2018-12-09 at 10 39 22 am 1](https://user-images.githubusercontent.com/918895/49700653-9efc8d00-fbaf-11e8-95e7-fd72b8a70a21.png)

**Comment by andr11111** [comment]
@alacret is this still an issue? Can I close?
